spring.application.name=LibraryTestApp

spring.datasource.url=jdbc:postgresql://localhost:5432/book_storage_service
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
