spring.application.name=book-storage-service
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.topic.name=book_topics

spring.datasource.url=jdbc:postgresql://localhost:5432/book_storage_service
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
